### ISSUE TITLE
Improve the container image override mechanism

### ISSUE THREAD

**Issue by aliok** [knative/eventing-operator#148]
**Problem**
As seen in https://github.com/knative/eventing/issues/2794, we cannot simply use the container names for overriding images for containers. Container names can be duplicated.

Current override mechanism is like this:

```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
...
spec:
  registry:
    override:
      eventing-controller: docker.io/my-eventing-controller
      eventing-webhook: docker.io/my-eventing-webhook
```

This cannot handle the case that we have for `imc-controller` and `broker-controller` deployments the same container name, `controller`.

My suggestion would be instead of  only providing the container name, we pass more information. Something like:

```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
...
spec:
  registry:
    overrides:
    - namespace: knative-eventing
      deployment: eventing-controller
      container: eventing-controller
      image: docker.io/my-eventing-controller
    - namespace: knative-eventing
      deployment: eventing-webhook
      container: eventing-webhook
      image: docker.io/my-eventing-webhook
```

This would fix the case that we have for `imc-controller` and `broker-controller` deployments the same container name, `controller`.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?
System admin

**Exit Criteria**
Proper image overriding, regardless of container names being unique or not.

**Time Estimate (optional):**
1 day

**Additional context (optional)**

See the causing ticket: https://github.com/knative/eventing/issues/2794

Related: https://github.com/knative/eventing-operator/issues/147
