### ISSUE TITLE
Unable to apply MF transforms properly

### ISSUE THREAD

**Issue by aliok** [knative/eventing-operator#157]
**Describe the bug**
Because of https://github.com/manifestival/manifestival/issues/33 image override transforms cannot be applied properly

**Expected behavior**
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  registry:
    override:
      eventing-controller: docker.io/foo/bar
```

would result in evening controller deployment's container to use `docker.io/foo/bar`

**To Reproduce**
Apply
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  registry:
    override:
      eventing-controller: docker.io/foo/bar
```

Check evening controller deployment's container. It doesn't use `docker.io/foo/bar`

**Knative release version**
Operator version 0.13

**Additional context**
Need to upgrade to Manifestival 0.4.0 as in serving here: https://github.com/knative/serving-operator/pull/338
