### ISSUE TITLE
Add the support to install event sources

### ISSUE THREAD

**Issue by houshengbo** [knative/eventing-operator#92]
**Describe the bug**
We cannot install any event resource available in https://github.com/knative/eventing-contrib.

**Expected behavior**
Install the event sources available in the repo eventing-contrib. Make the CR able to configure the list of event sources, to be installed in the knative eventing.

The custom resource will look like this:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  sources: github,kafka
```

We can use a comma separated string to specify all the event sources to be installed. Or use the following CR

```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  sources:
    -- github
    -- kafka
```
to specify the event sources in a list.
A key work "all" can be used to install all event sources.

**To Reproduce**
Steps to reproduce the behavior.

**Knative release version**
All.

**Additional context**
Add any other context about the problem here such as proposed priority
